dubai/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'dubai_.views.index'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^contact/','contato.views.contact'),
                       url(r'^register/','usuario.views.register'),
                       url(r'^login/','usuario.views.login_view'),
                       url(r'^logout/','usuario.views.logout_view'),
                       url(r'^news/(?P<slug>[\w_-]+)/$', 'imprensa.views.news_detail'),
                       url(r'^occurrence/', 'contato.views.occurrence'),
                       url(r'^gallery/', 'imprensa.views.gallery'),
                       url(r'^file/', 'imprensa.views.album'),
                       url(r'^download/(?P<id>[0-9]+)/$', 'imprensa.views.download'),
                       )+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

dubai_/models.py
from django.db import models

# Create your models here.

usuario/models.py
# -*- coding: utf-8 -*-
from encodings.punycode import selective_find
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from dubai.settings import EMAIL_HOST_USER
from django.core.mail import send_mail


class Condomino(User):
    class Meta:
        verbose_name = "Condômino"
        verbose_name_plural = 'Condôminos'
    BLOCO_TP = (
        ('1','JADE'),
        ('2','SAFIRA')
    )

    STATUS_MORADOR_TP = (
        ('1','PROPRIETÁRIO'),
        ('2','LOCATÁRIO')
    )
    identidade = models.CharField(max_length=25, unique=True)
    cpf = models.CharField(max_length=25, unique=True)
    telefone = models.CharField(max_length=25)
    bloco = models.CharField(max_length=1, choices=BLOCO_TP, verbose_name=unicode('Bloco'))
    status_morador = models.CharField(max_length=1, choices=STATUS_MORADOR_TP, verbose_name=unicode('Status'))
    numero = models.CharField(max_length=25, verbose_name=u'Número')

    def __unicode__(self):
        return (self.first_name)


def send_mail_condomino(sender, instance, **kwargs):
    if instance.is_active:
        email = instance.email
        send_mail('Solicitação de Cadastro', 'O seu cadastro foi aprovado. Agora você já pode utilizar os serviços do DUBAI RESIDENCE através do site www.condominiodubai.com.br.', EMAIL_HOST_USER, [email,], fail_silently=False)


post_save.connect(send_mail_condomino, sender=Condomino)

dubai_/forms.py
from django import forms
from contato.models import Contato


class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato

dubai_/views.py
# coding: utf-8
from django.template.context import RequestContext
from django.shortcuts import render_to_response
from imprensa.views import news_front
from slideshow.views import slide_home


def index(request):
    dados = {}
    dados['slider'] = slide_home()
    dados['news'] = news_front()
    print dados['slider']
    return render_to_response("index.html", dados,
                              context_instance=RequestContext(request))

dubai_/templates/about.html
<!DOCTYPE html>
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

<!-- Basic Page Needs -->
<meta charset="utf-8">
<title>Responsive Hotel  Site template</title>
<meta name="description" content="Responsive Hotel  Site template">
<meta name="author" content="">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- CSS -->
<link rel="stylesheet" href="css/base.css">
<link rel="stylesheet" href="css/menu.css">
<link rel="stylesheet" href="css/skeleton.css">
<link rel="stylesheet" href="css/layout.css">
<link rel="stylesheet" href="fontello/css/fontello.css">

<!-- prettyPhoto plugin -->
<link rel="stylesheet" href="js/prettyPhoto/css/prettyPhoto.css" type="text/css" media="screen">
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Favicons-->
<link rel="shortcut icon" href="images/favicon.ico">
<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

</head>
<body>
<header>
<div class="container">
	<div class=" four columns" id="logo"><a href="index.html">Paradise hotel</a></div>
	<div class="twelve columns">
		<ul id="lang">
			<li>En</li>
			<li><a href="#">Fr</a></li>
			<li><a href="#">Es</a></li>
		</ul>
		<div id="wxWrap"><span id="wxIntro">Currently here</span><span id="wxIcon2"></span><span id="wxTemp"></span></div><!-- weather -->
	</div>
    <!-- start main nav -->
	<div class="twelve columns">
		<nav>
		<ul id="main-nav" class="sf-menu">
			<li><a href="#">Home</a>
			<ul>
				<li><a href="index.html">Home slider</a></li>
				<li><a href="index_2.html">Home fullscreen</a></li>
			</ul>
			</li>
			<li><a href="rooms.html">Rooms</a></li>
			<li><a href="#">Pages</a>
			<ul>
				<li><a href="about.html">About</a></li>
				<li><a href="fullscreen_gallery.html">Fullscreen gallery</a></li>
				<li><a href="gallery.html">Gallery grids</a></li>
				<li><a href="rooms_2.html">Rooms 2</a></li>
			</ul>
			</li>
			<li><a href="../../contato/templates/contacts.html">Contact us</a></li>
			<li><a href="#">Purchase</a></li>
		</ul>
		</nav><!-- end main nav -->
	</div><!-- end twelve -->
</div><!-- end container -->
</header><!-- end header-->

<div class="container">
	<div class="sixteen columns add-bottom">
		<h1>About the hotel<span>Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores.</span></h1>
	</div>
    
	<div class="ten columns add-bottom">
		<div class="picture">
			<a href="img/about_1.jpg" data-rel="prettyPhoto"><span class="magnify"></span><img src="img/about_1.jpg" alt="picture" class="scale-with-grid"></a><em></em>
		</div>
		<h3>Ne has debet <span>Luvaret inciderint neglegentur qui ei</span></h3>
		<p>
			Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores. Ea insolens disputando ius, quo vidit dicta ne. Eu nobis accommodare vim, primis persius usu cu, te sed clita similique. Augue consul virtute ut eum, vide vocent in per. <strong>At legendos ullamcorper nec</strong>. Ad noster alienum per. Te nostrud menandri eam. Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores. Ea insolens disputando ius, quo vidit dicta ne.
		</p>
        <p>
			Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores. Ea insolens disputando ius, quo vidit dicta ne. Eu nobis accommodare vim, primis persius usu cu, te sed clita similique. Augue consul virtute ut eum, vide vocent in per. <strong>At legendos ullamcorper nec</strong>. Ad noster alienum per. Te nostrud menandri eam. Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores. Ea insolens disputando ius, quo vidit dicta ne.
		</p>
		<blockquote>
			 Augue consul virtute ut eum, vide vocent in per. At legendos ullamcorper nec. Ad noster alienum per. Te nostrud menandri eam.
		</blockquote>
		<p>
			Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores. Ea insolens disputando ius, quo vidit dicta ne. Eu nobis accommodare vim, primis persius usu cu, te sed clita similique.
		</p>
		<hr>
        
		<h3>Lorem ipsum dolor sit ame<span>Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores</span></h3>
		<p>
			Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores. Ea insolens disputando ius, quo vidit dicta ne. Eu nobis accommodare vim, primis persius usu cu, <a href="#">te sed clita similique.</a> Augue consul virtute ut eum, vide vocent in per. <em>At legendos ullamcorper ne</em>c. Ad noster alienum per. Te nostrud menandri eam. Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores. Ea insolens disputando ius, quo vidit dicta ne.
		</p>
		<p>
			Eu nobis accommodare vim, primis persius usu cu, te sed clita similique. Augue consul virtute ut eum, vide vocent in per. At legendos ullamcorper nec. Ad noster alienum per. Te nostrud menandri eam.
		</p>
		<hr>
        
		<iframe src="http://player.vimeo.com/video/26343407?byline=0&amp;portrait=0" width="100%" height="250"  class="add-bottom">
		</iframe>
		<h3>Eu nobis accommodare vim<span> Augue consul virtute ut eum, vide vocent in per</span></h3>
		<p>
			Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores. Ea insolens disputando ius, quo vidit dicta ne. Eu nobis accommodare vim, primis persius usu cu, te sed clita similique. Augue consul virtute ut eum, vide vocent in per. At legendos ullamcorper nec. Ad noster alienum per. Te nostrud menandri eam. Lorem ipsum dolor sit amet, per ne purto corpora, cu eam cetero dolores. Ea insolens disputando ius, quo vidit dicta ne. Eu nobis accommodare vim, primis persius usu cu, te sed clita similique.
		</p>
	</div><!-- end ten columns-->
    
    <!-- start right column-->
	<div class="five columns offset-by-one add-bottom">
    
		<h4 id="swim">Swimming pool</h4>
		<div class="three columns alpha">
			<img src="img/poll.jpg" alt="" class="scale-with-grid half-bottom" >
		</div>
		<br class="clear">
		<p>
			Vix in error iuvaret, at omnium prompta aliquam vel. Sea an purto vide posidonium, eos modus dicit ne. Appetere dignissim vis et.
		</p>
        
		<h4 id="restaurant">Restaurant</h4>
		<div class="three columns alpha">
			<img src="img/restaurant.jpg" alt="" class="scale-with-grid half-bottom" >
		</div>
		<br class="clear">
		<p>
			Vix in error iuvaret, at omnium prompta aliquam vel. Sea an purto vide posidonium, eos modus dicit ne. Appetere dignissim vis et.
		</p>
        
		<h4 id="bar">Cocktail Bar</h4>
		<div class="three columns alpha">
			<img src="img/bar.jpg" alt="" class="scale-with-grid half-bottom">
		</div>
		<br class="clear">
		<p>
			Vix in error iuvaret, at omnium prompta aliquam vel. Sea an purto vide posidonium, eos modus dicit ne. Appetere dignissim vis et.
		</p>
        
		<h4 id="sports">Sports</h4>
		<ul class="list_4">
			<li>Vix in error iuvaret, at omnium prompta aliquam vel. Sea an purto vide posidonium, eos modus dicit ne. Appetere dignissim vis et. </li>
			<li>Appetere dignissim vis et. Te per dolore expetenda voluptaria, an eam autem perfecto patrioque. Eu eum inermis verterem assentior.</li>
			<li>Vix in error iuvaret, at omnium prompta aliquam vel. Sea an purto vide posidonium, eos modus dicit ne. Appetere dignissim vis et. </li>
			<li>Appetere dignissim vis et. Te per dolore expetenda voluptaria, an eam autem perfecto patrioque. Eu eum inermis verterem assentior.</li>
		</ul>
	</div><!-- end right column-->
</div><!-- end container -->

<footer>
    <div class="container">
        <nav class="eleven columns">
        <ul id="nav-footer">
            <li><a href="rooms.html">Rooms</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="rooms.html">Book now</a></li>
            <li><a href="fullscreen_gallery.html">Gallery</a></li>
            <li><a href="../../contato/templates/contacts.html">Contacts </a></li>
        </ul>
        </nav>
    <div class="five columns copy">© 2012 Paradise Hotel. All Rights Reserved.</div>
    </div>
</footer><!-- footer  -->
<!-- Jquery -->
<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<!-- JQUERY plugins: Moderniz, Prettyphoto, Flexislider, MobileMenu, SuperfishMenu, Weather, Tooltip-->	
<script type="text/javascript"  src="js/plug_ins.js"></script>
<!-- Google Maps API -->	
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="js/google_map.js"></script>
<script src="js/functions.js"></script>
</body>
</html>

dubai_/templates/album.html
{% extends "base.html" %}
{% load i18n static  staticfiles%}
{% load thumbnail %}

{% block slider %}
    <div class="container">
        <div class="sixteen columns add-bottom">
            <h1>Pastas</h1>
        </div>
        <section class="sixteen columns">
            <div class="add-bottom">
                {% for a in album %}
                    <a href="/download/{{ a.id }}/" ><img src="{% static "img/document-icon.png"%}" alt="picture" class="scale-with-grid">
                        <h3>{{ a.nome }}</h3></a>
                    <p>{{ a.descricao }}</p>
                    <hr>
                {% endfor %}
                <br class="clear">
            </div>
        </section>
    </div>
{% endblock %}

dubai_/templates/base.html
<!DOCTYPE html>
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
{% load i18n static  staticfiles%}


{% block css %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static "css/base.css"%}">
    <link rel="stylesheet" href="{% static "css/skeleton.css"%}">
    <link rel="stylesheet" href="{% static "css/menu.css"%}">
    <link rel="stylesheet" href="{% static "css/flexslider.css"%}">
    <link rel="stylesheet" href="{% static "css/layout.css"%}">
    <link rel="stylesheet" href="{% static "fontello/css/fontello.css"%}">
    <!-- prettyPhoto plugin -->
    <link rel="stylesheet" href="{% static "js/prettyPhoto/css/prettyPhoto.css"%}" type="text/css" media="screen">
    <!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

    <!-- Favicons-->
    <link rel="shortcut icon" href="{% static "img/favicon.ico"%}">
    <link rel="apple-touch-icon" href="{% static "img/apple-touch-icon.png"%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static "img/apple-touch-icon-72x72.png"%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static "img/apple-touch-icon-114x114.png"%}">
{% endblock %}


<head>
    {% block head %}
        <!-- Basic Page Needs -->
        <meta charset="utf-8">
        <title>{% block title %}Dubai Residence{% endblock %}</title>
        <meta name="description" content="Dubai Residence">
        <meta name="author" content="">
        <!-- Mobile Specific Metas -->
    {% endblock %}
</head>

<body>
{% block header %}
    <header>
        <div class="container">
            <div class="four columns" id="logo"><a href="/">Dubai Residence</a></div>
            {% if user.is_authenticated %}
                <div class="twelve columns">
                    <ul id="lang">
                        <li>{{ user.username }}</li>
                        <li><a href="/logout/">Sair</a></li>
                    </ul>
                </div>
            {% endif %}
            <!-- start main nav -->
            <div class="twelve columns">
                <nav>
                    <ul id="main-nav" class="sf-menu">

                        <!-- Caso o usuário estiver logado. -->
                        {% if user.is_authenticated %}
                            <li><a href="/">Home</a></li>
                            <li><a href="/gallery/">Galeria</a></li>
                            <li><a href="/file/">Documentos</a></li>
                            <li><a href="/occurrence/">Ocorrência</a></li>
                            <li><a href="/contact/">Contato</a></li>
                        {% else %}
                            <li><a href="/">Home</a></li>
                            <li><a href="/gallery/">Galeria</a></li>
                            <li><a href="/contact/">Contato</a></li>
                            <li><a href="#">Acesso</a>
                                <ul>
                                    <li><a href="/login/">Login</a></li>
                                    <li><a href="/register/">Cadastro</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                </nav><!-- end main nav -->
            </div><!-- end twelve -->
        </div><!-- end container -->
    </header><!-- end header-->
{% endblock %}

<!-- slideshow -->
{% block slider %}
{% endblock %}
<!-- slideshow -->

<!-- reservas -->
{% block grey_bg %}
{% endblock %}
<!-- reservas -->

<!-- info -->
{% block hotel_info %}
{% endblock %}
<!-- info -->

{% block footer %}
    <footer>
        <div class="container">
            <nav class="eleven columns">
                <ul id="nav-footer">
                    {% if user.is_authenticated %}
                        <li><a href="/">Home</a></li>
                        <li><a href="/gallery/">Galeria</a></li>
                        <li><a href="/file/">Documentos</a></li>
                        <li><a href="/occurrence/">Ocorrência</a></li>
                        <li><a href="/contact/">Contato</a></li>
                    {% else %}
                        <li><a href="/">Home</a></li>
                        <li><a href="/gallery/">Galeria</a></li>
                        <li><a href="/contact/">Contato</a></li>
                        <li><a href="/login/">Acesso</a></li>
                    {% endif %}
                </ul>
            </nav>
            <div class="five columns copy">© Dubai Residence. Todos os direitos reservados.</div>
        </div>
    </footer><!-- footer  -->
{% endblock %}
{% block js %}
    <!-- Jquery -->
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="{% static "js/flexi_slider.js"%}"></script>
    <script type="text/javascript">
        $(window).load(function() {
            $('.flexslider').flexslider();
        });
    </script>
    <!-- JQUERY plugins: Moderniz, Prettyphoto, Flexislider, MobileMenu, SuperfishMenu, Weather, Tooltip-->
    <script type="text/javascript"  src="{% static "js/plug_ins.js"%}"></script>
    <!-- Google Maps API -->
    {#    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>#}
    <script type="text/javascript" src="{% static "js/google_map.js"%}"></script>
    <script src="{% static "js/functions.js"%}"></script>
    <script type="text/javascript" src="{% static "js/jquery.maskedinput.js"%}"></script>
    <script type="text/javascript">
        jQuery(function($) {
            $.mask.definitions['~']='[+-]';
            $('#date').mask('99/99/9999');
            $('#id_telefone').mask('(99) 99999-9999');
            $('#id_cpf').mask('999.999.999-99');
        });
    </script>
{% endblock %}
</body>
</html>

dubai_/templates/download.html
{% extends "base.html" %}
{% load i18n static  staticfiles%}
{% load thumbnail %}

{% block slider %}
    <div class="container">
        <div class="sixteen columns add-bottom">
            <h1>Download<span>Tenha os arquivos do seu condomínio com maior facilidade.</span></h1>
        </div>
        <div class="eleven columns">
            {% for d in download %}
                <!-- start room -->
                <div class="four columns picture alpha">
                    {% if d.get_extensao == 'pdf' %}
                        <a href={{ MEDIA_URL }}{{ d.arquivo }} ><img src="{% static "img/pdf-icon.png"%}" alt="" class="scale-with-grid"></a><em></em>
                    {% elif d.get_extensao == 'xls' %}
                        <a href={{ MEDIA_URL }}{{ d.arquivo }} ><img src="{% static "img/excel-xls-icon.png"%}" alt="" class="scale-with-grid"></a><em></em>
                    {% elif d.get_extensao == 'png' %}
                        <a href={{ MEDIA_URL }}{{ d.arquivo }} > <img src="{% static "img/png-icon.png"%}" alt="" class="scale-with-grid"></a><em></em>
                    {% elif d.get_extensao == 'word' %}
                        <a href={{ MEDIA_URL }}{{ d.arquivo }} ><img src="{% static "img/word-doc-icon.png"%}" alt="" class="scale-with-grid"></a><em></em>
                    {% elif d.get_extensao == 'zip' %}
                        <a href={{ MEDIA_URL }}{{ d.arquivo }} ><img src="{% static "img/zip-icon.png"%}" alt="" class="scale-with-grid"></a><em></em>
                    {% elif d.get_extensao == 'jpg' %}
                        <a href={{ MEDIA_URL }}{{ d.arquivo }} > <img src="{% static "img/jpg-icon.png"%}" alt="" class="scale-with-grid"></a><em></em>
                    {% elif d.get_extensao == 'ppt' %}
                        <a href={{ MEDIA_URL }}{{ d.arquivo }} ><img src="{% static "img/ppt-icon.png"%}" alt="" class="scale-with-grid"></a><em></em>
                    {% else %}
                        <a href={{ MEDIA_URL }}{{ d.arquivo }} ><img src="{% static "img/unknown-icon.png"%}" alt="" class="scale-with-grid"></a><em></em>
                    {% endif %}
                </div>
                <div class="seven columns omega">
                    <h3>{{ d.titulo }}<span> {{ d.data }}</span></h3>
                    <p>{{ d.descricao }}</p>
                    <br class="clear add-bottom"/>
                </div><!-- end  room-->
                <hr>
            {% endfor %}
            {% if not download %}
                <!-- start room -->
                <div class="four columns picture alpha">
                    <img src="{% static "img/pdf-icon.png"%}" alt="" class="scale-with-grid"><em></em>
                </div>
                <div class="seven columns omega">
                    <h3>Atenção<span>Não há arquivos para download nessa pasta.</span></h3>
                    <br class="clear add-bottom"/>
                </div><!-- end  room-->
            {% endif %}
        </div><!-- end column left - rooms list -->

        <!-- start col right -->
        <section class="five columns omega">
            <div class="facilities_desc add-bottom_2">
                <ul>
                    {% for a in album %}
                        <li>
                            <a href="/download/{{ a.id }}/" > <h5>{{ a.nome }}</h5></a>
                            <p>{{ a.descricao|safe|truncatechars:28 }}</p>
                        </li>
                    {% endfor %}
                </ul>
            </div><!-- end facilities desc-->
        </section><!-- end col right -->
    </div>
{% endblock %}

dubai_/templates/fullscreen_gallery.html
<!DOCTYPE html>
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

<!-- Basic Page Needs -->
<meta charset="utf-8">
<title>Responsive Hotel  Site template</title>
<meta name="description" content="Responsive Hotel  Site template">
<meta name="author" content="">

<!-- Mobile Specific Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- CSS -->
<link rel="stylesheet" href="css/base.css">
<link rel="stylesheet" href="css/skeleton.css">
<link rel="stylesheet" href="css/menu.css">
<link rel="stylesheet" href="css/layout.css">
<link rel="stylesheet" href="css/supersized.css" type="text/css" >
<link rel="stylesheet" href="theme/supersized.shutter.css" type="text/css" >
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Favicons-->
<link rel="shortcut icon" href="img/favicon.ico">
<link rel="apple-touch-icon" href="img/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="img/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="img/apple-touch-icon-114x114.png">
	
</head>
<body class="full"><!--  This class call different styles only for this page --> 
<header>
<div class="container">
	<div class=" four columns" id="logo"><a href="index.html">Paradise hotel</a></div>
	<div class="twelve columns">
	<ul id="lang">
		<li><a href="#">En</a></li>
		<li><a href="#">Fr</a></li>
		<li><a href="#">Es</a></li>
	</ul>
    <div id="back"><a href="index.html">Back to home</a></div><!--  Back button for Mobile --> 
    <div id="wxWrap"><span id="wxIntro">Currently here</span><span id="wxIcon2"></span><span id="wxTemp"></span></div>
</div>
<!-- start main nav -->
	<div class="twelve columns">
		<nav>
		<ul id="main-nav" class="sf-menu">
			<li><a href="#">Home</a>
			<ul>
				<li><a href="index.html">Home slider</a></li>
				<li><a href="index_2.html">Home fullscreen</a></li>
			</ul>
			</li>
			<li><a href="rooms.html">Rooms</a></li>
			<li><a href="#">Pages</a>
			<ul>
				<li><a href="about.html">About</a></li>
				<li><a href="fullscreen_gallery.html">Fullscreen gallery</a></li>
				<li><a href="gallery.html">Gallery grids</a></li>
				<li><a href="rooms_2.html">Rooms 2</a></li>
			</ul>
			</li>
			<li><a href="../../contato/templates/contacts.html">Contact us</a></li>
			<li><a href="#">Purchase</a></li>
		</ul>
		</nav><!-- end main nav -->
	</div><!-- end twelve -->
</div><!-- end container -->
</header><!-- end header-->
             
     <!--Arrow Navigation-->
	<a id="prevslide" class="load-item"></a>
	<a id="nextslide" class="load-item"></a>
    <div id="slidecaption" ></div>
<!-- Jquery -->
<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>	
<!-- JS -->
<script type="text/javascript" src="js/jquery.easing.min.js"></script>
<script type="text/javascript" src="js/supersized.3.2.6.min.js"></script>
<script type="text/javascript" src="theme/supersized.shutter.min.js"></script>
<script type="text/javascript" src="js/bg_images.js"></script><!--Set your images and captions here --> 

<!-- JQUERY plugins: Moderniz, SuperfishMenu, Weather-->	
<script type="text/javascript"  src="js/plug_ins_2.js"></script>  <!--Plugins file only for this page --> 
<script src="js/functions_2.js"></script><!--Functions file only for this page --> 
</body>
</html>

dubai_/templates/gallery.html
{% extends "base.html" %}
{% load i18n static  staticfiles%}
{% load thumbnail %}

{% block slider %}
    <div class="container">
        <div class="sixteen columns add-bottom">
            <h1>Galeria</h1>
        </div>
        <section class="sixteen columns">
        </section>
        <div class="add-bottom">
            {% for g in gallery %}
                <div class="one-third column picture loader">
                    {% thumbnail g.foto "700" crop="center" as big %}
                        <a href={{ MEDIA_URL }}{{ big }} data-rel="prettyPhoto[photo]" title="" >
                    {% endthumbnail %}
                    {% thumbnail g.foto "300" crop="center" as small %}
                        <img src={{ MEDIA_URL }}{{ small }} alt="" class="scale-with-grid"><span class="magnify"></span><em></em></a>
                    {% endthumbnail %}
                </div>
            {% endfor %}
            <br class="clear">
        </div>
    </div>
{% endblock %}

dubai_/templates/message.html
{% extends "base.html" %}
{% load i18n static  staticfiles%}

{% block slider %}
    <div class="container add-bottom_2">
        <div class="sixteen columns add-bottom">
            <h1>{{ data.message }}<span>{{ data.spam }}</span></h1>
        </div>
        <img src="{% static "img/obrigado.png"%}" alt="picture" class="scale-with-grid">
    </div>
{% endblock %}